name: Terraform validate

on:
  push:
    branches: [ "main" ]

jobs:
  tf_code_check:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init and validate
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init

        echo "** Running Terraform Validate**"
        terraform validate
